// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhosNext_Infra.Context;

#nullable disable

namespace WhosNextInfra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230201003142_Seed")]
    partial class Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhosNext_Domain.Account.AccountDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AcceptIncommings")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpperId")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UpperId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcceptIncommings = false,
                            CreatedAt = new DateTime(2023, 1, 31, 21, 31, 42, 623, DateTimeKind.Local).AddTicks(8366),
                            ExternalCode = "1",
                            Name = "Receita"
                        },
                        new
                        {
                            Id = 2,
                            AcceptIncommings = false,
                            CreatedAt = new DateTime(2023, 1, 31, 21, 31, 42, 623, DateTimeKind.Local).AddTicks(8381),
                            ExternalCode = "2",
                            Name = "Despesas"
                        },
                        new
                        {
                            Id = 3,
                            AcceptIncommings = false,
                            CreatedAt = new DateTime(2023, 1, 31, 21, 31, 42, 623, DateTimeKind.Local).AddTicks(8382),
                            ExternalCode = "2.1",
                            Name = "Com pessoal",
                            UpperId = 2
                        },
                        new
                        {
                            Id = 4,
                            AcceptIncommings = false,
                            CreatedAt = new DateTime(2023, 1, 31, 21, 31, 42, 623, DateTimeKind.Local).AddTicks(8383),
                            ExternalCode = "2.2",
                            Name = "Mensais",
                            UpperId = 2
                        },
                        new
                        {
                            Id = 5,
                            AcceptIncommings = false,
                            CreatedAt = new DateTime(2023, 1, 31, 21, 31, 42, 623, DateTimeKind.Local).AddTicks(8384),
                            ExternalCode = "2.3",
                            Name = "Manutenção",
                            UpperId = 2
                        },
                        new
                        {
                            Id = 6,
                            AcceptIncommings = false,
                            CreatedAt = new DateTime(2023, 1, 31, 21, 31, 42, 623, DateTimeKind.Local).AddTicks(8385),
                            ExternalCode = "2.4",
                            Name = "Diversas",
                            UpperId = 2
                        },
                        new
                        {
                            Id = 7,
                            AcceptIncommings = false,
                            CreatedAt = new DateTime(2023, 1, 31, 21, 31, 42, 623, DateTimeKind.Local).AddTicks(8386),
                            ExternalCode = "3",
                            Name = "Despesas bancárias"
                        },
                        new
                        {
                            Id = 8,
                            AcceptIncommings = false,
                            CreatedAt = new DateTime(2023, 1, 31, 21, 31, 42, 623, DateTimeKind.Local).AddTicks(8387),
                            ExternalCode = "4",
                            Name = "Outras receitas"
                        });
                });

            modelBuilder.Entity("WhosNext_Domain.Account.AccountDomain", b =>
                {
                    b.HasOne("WhosNext_Domain.Account.AccountDomain", "Upper")
                        .WithMany("Lowers")
                        .HasForeignKey("UpperId");

                    b.Navigation("Upper");
                });

            modelBuilder.Entity("WhosNext_Domain.Account.AccountDomain", b =>
                {
                    b.Navigation("Lowers");
                });
#pragma warning restore 612, 618
        }
    }
}
